name: SQA Invoke

on:
  push:
    branches:
      - main

jobs:
  invoke_curl_request:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Curl Request
        run: |
          curl -X GET -H "Content-Type: application/json" https://simplify3x.com
